default:
  image: node:apline
  before_script:
    - echo Hello World


stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  tags:
    - sulg

pages:
  stage: deploy
  script:
    - ls
    - rm -rf public
    - ls
    - mkdir public && cp -rf dist/* public
    - ls public
  tags:
    - sulg
  artifacts:
    paths:
      - public
    expire_in: 30 days


cache:
  paths:
    - node_modules
    - dist
