building: 
  image: node:15.7.0-alpine3.10
  stage: build
  script
    - npm install --progress=false --no-optional
    - npm run build
  artifacts:
    expire_in: 7 days
    paths: 
      - dist 

cache: 
  paths: 
    - node_modules/ 

pages: 
  stage: deploy 
  script: 
    - rm -rf public/* 
  artifacts: 
    expire_in: 7 days
    paths: //路径
      - public 
  only: 
    - master